apiVersion: v1
kind: Secret
metadata:
  name: jira-creds
  namespace: jira-stats
type: Opaque
data:
  jira_user: "{{ JIRA_USER_BASE64 }}"
  jira_password: "{{ JIRA_PASSWORD_BASE64 }}"
  jira_uri: "{{ JIRA_URI_BASE64 }}"
